[package]
name = "physics-sim"
version = "0.1.0"
authors = ["Josh Hejna <josh.hejna@gmail.com>"]

[dependencies]
alga = "0.7.2"
dimensioned = "0.7.0"


[dev-dependencies]
# nalgebra = "0.16.2"
assert_approx_eq = "1.0.0"
csv = "1"
serde = "1.0"
